---
version: 0.1

phases:
  install:
    commands:
      - pip3 install requests
  pre_build:
    commands:
      - echo "Python version"
      - python3 --version
      - pwd
      - PACKER_INSTALL_LOCATION="$(pwd)/"
      - echo $PACKER_INSTALL_LOCATION
      - echo "Get latest version of Hashicorp packer using hashicorp-get tooling"
      - wget https://raw.githubusercontent.com/brian-provenzano/hashicorp-get/master/hashicorp-get.py
      - chmod +x hashicorp-get.py && python3 ./hashicorp-get.py packer latest -q -y $PACKER_INSTALL_LOCATION
      # - echo "Installing jq..."
      # - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Validating Basic-WebPHP-EC2AMI.json"
      - ./packer validate Basic-WebPHP-EC2AMI.json
  build:
    commands:
      ### HashiCorp Packer cannot currently obtain the AWS CodeBuild-assigned role and its credentials
      ### Manually capture and configure the AWS CLI to provide HashiCorp Packer with AWS credentials
      ### More info here: https://github.com/mitchellh/packer/issues/4279
      # - echo "Configuring AWS credentials"l
      # - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      # - aws configure set region $AWS_REGION
      # - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      # - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      # - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building HashiCorp Packer template, amazon-linux_packer-template.json"
      - ./packer build Basic-WebPHP-EC2AMI.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"