---
version: 0.1

# use with custom alpine docker image in the ecr

phases:
  pre_build:
    commands:
      #- export PACKER_POSTPROCESS=get-ami.sh
      #- echo $PACKER_POSTPROCESS
      - echo "Validating Basic-WebPHP-EC2AMI.json for format"
      - packer validate -var 'postscript=get-ami.sh' Basic-WebPHP-EC2AMI.json
  build:
    commands:
      - echo "Building HashiCorp Packer template, amazon-linux_packer-template.json"
      - packer build -var 'postscript=get-ami.sh' Basic-WebPHP-EC2AMI.json
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"
      - echo "Image Created:"
      - cat ami.txt
      - aws ec2 describe-images --image-ids $(cat ami.txt | tr -d \'[:space:]\')
      - echo "TODO - cleanup old AMIs (x many versions); delete snapshots associated with old AMI (already have this in my personal repo)"
